### ISSUE TITLE
Improve how to gen TIL README

### ISSUE THREAD

**Issue by kevintruong** [simonw/til#10]
Really love your ideal on create TIL. The same as you, I inspired by Josh Branchaud also. 
But looking at your update_readme process. I think we can do better. 
If you interested, please take a look on my work. fork from you script. But adding some info. Then we don't need to create database first. 
https://github.com/kevintruong/kevin-blogs/blob/master/content/TIL/build_home.py
Any comment is welcome. 
Thanks for inspired me. 
Kevin Truong

**Comment by simonw** [comment]
Your approach is certainly neater if you don't want to create the database. In my case I'm continuing on my quest to convince the world to do everything with SQLite (even when they don't need to) so I'm going to leave my implementation as-is.

Really glad to see you taking this concept and making it your own!
