### ISSUE TITLE
Screenshot 404s upon 

### ISSUE THREAD

**Issue by kaihendry** [simonw/til#29]
https://til.simonwillison.net/til/til/firefox_search-across-all-resources.md

I use https://ohdear.app/ to keep tabs on my link rot. Not sure there is a better way?

**Comment by simonw** [comment]
Thanks, fixed that page. I could add some tests for that as part of the build script - may do that next time I'm tweaking it.

**Comment by kaihendry** [comment]
Ah you store/serve media from Github? Was curious about https://github.com/simonw/til/blob/main/metadata.yaml#L9

**Comment by simonw** [comment]
That's just for the screenshots of the posts that I use in the social media cards - they go in SQLite BLOBs. The images in posts currently go straight in the repository.
