### ISSUE TITLE
Make the feed valid with links

### ISSUE THREAD

**Issue by davidbgk** [simonw/til#9]
I realized, trying to click on an entry of the feed that my aggregator wasn't following any URL because… there was none :).

See https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ftil.simonwillison.net%2Ftil%2Ffeed.atom%3F_feed_title%3DSimon%2520Willison%2520TIL for details.

**Comment by simonw** [comment]
Oops, thanks for pointing this out!

**Comment by davidbgk** [comment]
It's still invalid but at least there is a link now 👍
